### ISSUE TITLE
Csgowinbig steambot invalid URI error

### ISSUE THREAD

**Issue by nickbijmoer** [ztizzlegaming/CSGOWinBig#196]
Hello, I get a invalid URI error after accepting an offer, this is the error from the log, I already tried change the website url in settings.json but it didnt help:

ERROR: System.UriFormatException: Invalid URI: The format of the URI could not be determined.
at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
at System.Uri..ctor(String uriString)
at System.Net.WebRequest.Create(String requestUriString)
at SteamBot.DepositTradeOfferUserHandler.OnNewTradeOffer(TradeOffer offer) in c:\Users\nickbijmoer\Desktop\SteamBot-master\SteamBot\DepositTradeOfferUserHandler.cs:line 239
at SteamBot.Bot.TradeOfferRouter(TradeOffer offer) in c:\Users\nickbijmoer\Desktop\SteamBot-master\SteamBot\Bot.cs:line 1011
at SteamTrade.TradeOffer.TradeOfferManager.SendOfferToHandler(Offer offer) in c:\Users\nickbijmoer\Desktop\SteamBot-master\SteamTrade\TradeOffer\TradeOfferManager.cs:line 142
at SteamTrade.TradeOffer.TradeOfferManager.GetActiveTradeOffers() in c:\Users\nickbijmoer\Desktop\SteamBot-master\SteamTrade\TradeOffer\TradeOfferManager.cs:line 48
at SteamTrade.TradeOffer.TradeOfferManager.GetOffers() in c:\Users\nickbijmoer\Desktop\SteamBot-master\SteamTrade\TradeOffer\TradeOfferManager.cs:line 121
at SteamBot.Bot.UserWebLogOn() in c:\Users\nickbijmoer\Desktop\SteamBot-master\SteamBot\Bot.cs:line 901
at SteamBot.Bot.b__5(LoginKeyCallback callback) in c:\Users\nickbijmoer\Desktop\SteamBot-master\SteamBot\Bot.cs:line 536
at SteamKit2.CallbackMsgExtensions.HandleT
at SteamBot.Bot.HandleSteamMessage(ICallbackMsg msg) in c:\Users\nickbijmoer\Desktop\SteamBot-master\SteamBot\Bot.cs:line 532
at SteamBot.Bot.BackgroundWorkerOnDoWork(Object sender, DoWorkEventArgs doWorkEventArgs) in c:\Users\nickbijmoer\Desktop\SteamBot-master\SteamBot\Bot.cs:line 1220

Anyone who could help me?

**Comment by ICallHax** [comment]
It just means that in your settings file for the bot you put an invalid URL. What is your URL currently in your settings?

**Comment by nickbijmoer** [comment]
TheAnthonyNL helped me yesterday it is now fixed, I think my problem was that i didnt put http:// in front of the botwebsiteurl

**Comment by ICallHax** [comment]
Ya your URL should be in this format http://www.yoururl.com
<http://www.csgofancy.com/> I believe
